import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, UserButton, UserProfile, useUser } from "@clerk/nextjs";

export default function Home() {
  const postsResponse = api.posts.getAll.useQuery()

  console.log(postsResponse.isError)

  const { isSignedIn, user } = useUser()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-slate-200">
        {isSignedIn && <UserButton />}
        <div>
          isFetching {String(postsResponse.isFetching)}
          <br />
          isError {String(postsResponse.isError)}
          {postsResponse.data?.map(post =>
            <div key={post.id}>{post.content}</div>
          )}
        </div>
        {!isSignedIn && <SignInButton />}
      </main>
    </>
  );
}
