name: CI

on: [push, pull_request]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # specify your required node version here

      - name: Install PNPM
        run: |
          curl -f https://get.pnpm.io/v6.js | node - add --global pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript type checking
        run: pnpm run typecheck # make sure you have a typecheck script in your package.json

      - name: Run Lint
        run: pnpm run lint # make sure you have a lint script in your package.json
